# Generated by Django 3.0.5 on 2020-04-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
