# Generated by Django 3.0.5 on 2020-04-28 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_task_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(default='food', max_length=200)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('complete', models.BooleanField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(default='home', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
