# Generated by Django 3.0.5 on 2020-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_messages_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='colour',
            field=models.CharField(blank=True, default='#fcba03', max_length=150),
        ),
    ]
