# Generated by Django 3.0.5 on 2020-04-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_dinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
