# Generated by Django 3.0.5 on 2020-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_dinner_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(default='other', max_length=200),
        ),
    ]
